baseurl = "https://bloxtop.gitHub.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "BloxTop"
theme = "dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

#summaryLength = 20

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "BloxTop"
  # description = ""
  avatar = "/img/bloxtop.jpg"
  motto = "A place for cryptocurrency"

  email = "bloxtop@outlook.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020


  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true
